version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    ports:
      - 9090:9090

  alertmanager:
    ports:  
      - 9093:9093

  nodeexporter:
    ports:
      - 9100:9100

  cadvisor:
    ports:
      - 8080:8080

  grafana:
    ports:
      - 3000:3000

  pushgateway:
    ports:
      - 9091:9091

